version: '3.8'

services:
  # 管理平台后端
  platform-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: gpu-platform-backend
    ports:
      - "8080:8080"
    volumes:
      - ./platform.db:/app/platform.db
      - ./users:/app/users
      - ./shared:/app/shared
      - ./workspace:/app/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=8080
      - DB_PATH=platform.db
    restart: unless-stopped
    networks:
      - platform-network

  # 开发环境镜像构建服务
  dev-env-builder:
    build:
      context: ./docker
      dockerfile: Dockerfile.dev
    image: gpu-dev-env:latest
    container_name: gpu-dev-env-builder
    profiles:
      - build-only
    command: "echo 'Development environment image built successfully'"

networks:
  platform-network:
    driver: bridge

volumes:
  platform-data:
    driver: local