#version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: gpu-platform-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gpu_platform
      MYSQL_USER: platform
      MYSQL_PASSWORD: platform123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "platform", "-pplatform123"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s
    restart: unless-stopped
    networks:
      - platform-network

  # 管理平台后端
  platform-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: gpu-platform-backend
    ports:
      - "8080:8080"
    volumes:
      - ./users:/app/users
      - ./shared:/app/shared
      - ./workspace:/app/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PORT=8080
      - DB_DSN=platform:platform123@tcp(mysql:3306)/gpu_platform?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - platform-network

  # 开发环境镜像构建服务
  dev-env-builder:
    build:
      context: ./docker
      dockerfile: Dockerfile.dev
    image: gpu-dev-env:latest
    container_name: gpu-dev-env-builder
    profiles:
      - build-only
    command: "echo 'Development environment image built successfully'"

networks:
  platform-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local